In [1]:
!pip3 install numpy 

In [2]:
!pip3 install --upgrade pip

In [1]:
print('hello')

hello


In [8]:
import numpy as np
# numpy is used for numerical processing
arr =np.array([[1,2,3],[4,5,6]])
type(arr)
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
arr.ndim

2

In [8]:
arr.shape

(2, 3)

In [5]:
#r,col = arr.shape
# If the shape is 1-d , then only (n,) is the answer , n- number of elements
# numpy array can be created using tuples


In [9]:
ans=np.ones((5,5))
print(ans)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
np.eye(3)
# default datatype of np.eye is float 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# np.arange return evenly spaced values within a given interval. It returns sequence of integers from 0 to 30 with steps of 5
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [14]:
np.linspace(0,5,10)
# prints sequence of 10 values between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
a = np.array([[4,3,2,1],[5,6,7,8],[9,10,11,12]])
new = a.reshape((2,2,3))
print(new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
# flatten function converts an n-d array to an 1-d array
flat = a.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
# In np array , indexing will be arr[row,column] , where ,arr[start:stop:step , start:stop:step]
## Numpy arrays have broadcasting feature .It means that ,an array operation will change all the elements of the array 
# In numpy we have max , min ,cumsum , sum ,etc..
print(a.max(axis=0)) # vertical max
print(a.min(axis=1)) # horizontal min
print(a.cumsum()) # print the cumulative sum of the numpy array
print(a.sum()) # print the sum of the numpy array

# Sorting Operations 
print(np.sort(a,axis =0)) # vertical sort
print(np.sort(a,axis=1)) #horizontal sort

# Sorting can also be done , by mentioning different kinds of sorting 

[ 9 10 11 12]
[1 5 9]
[ 1  3  6 10 15 21 28 36 45 55 66 78]
78
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
