# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [6]:
import numpy as np
print(np.__version__)
print(np.__config__)

1.19.5
<module 'numpy.__config__' from 'c:\\python\\python39\\lib\\site-packages\\numpy\\__config__.py'>


#### 3. Create a null vector of size 10

In [7]:
x =np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [8]:
 print(x.size) # Size function is used for finding the memory size of an array

10


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [2]:
 #run the command python -c "import numpy; help(numpy.add)" in command prompt

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [9]:
ans =np.zeros(10)
ans[4]=1
print(ans)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [11]:
arr =np.zeros(40)
for i in range (0,arr.size):
    arr[i]=i+10
print(arr)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
arr =np.zeros(40)
for i in range (0,arr.size):
    arr[i]=i+10
print(arr)
print(arr[::-1])

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]
[49. 48. 47. 46. 45. 44. 43. 42. 41. 40. 39. 38. 37. 36. 35. 34. 33. 32.
 31. 30. 29. 28. 27. 26. 25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14.
 13. 12. 11. 10.]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
import numpy as np
ans = np.arange(9).reshape(3,3)
print(ans)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [9]:
nonzero = np.nonzero([1,2,0,0,4,0])
print(nonzero)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [10]:
z =np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [11]:
numpy_array = np.random.random((3,3,3))
print(numpy_array)

[[[0.08844437 0.45460277 0.94922122]
  [0.25238709 0.2898235  0.82533406]
  [0.00833164 0.17871375 0.62196671]]

 [[0.18807787 0.7239396  0.78635971]
  [0.01959366 0.38331367 0.09154031]
  [0.16059195 0.06990357 0.78660971]]

 [[0.51520288 0.10436597 0.66328695]
  [0.40840926 0.25619505 0.52402252]
  [0.77937121 0.0487496  0.53668096]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [15]:
rand_np = np.random.random((10,10))
print(rand_np.max())
print(rand_np.min())

0.9886352674798818
0.015957877074647908


#### 14. Create a random vector of size 30 and find the mean value

In [19]:
mean_np = np.random.random((30))
print(mean_np.mean())


0.5261842942041367


#### 15. Create a 2d array with 1 on the border and 0 inside

In [25]:
border = np.ones((5,5))
border[1:-1,1:-1] =0
print(border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [31]:
border_zero = np.ones((5,5))
'''border_zero[0] =0
border_zero[4] =0
border_zero[0:,4] =0
border_zero[0:,0] =0'''
border_zero =np.pad(z,pad_width =1,mode ='constant',constant_values=0)


print(border_zero)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [24]:
# Output : nan , false , false , nan ,true , false 
# If the whole code is executed output will be false 



nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [35]:
diag = np.zeros((5,5))
diag = np.diag(1+np.arange(4),k=-1)
print(diag)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [34]:
checker= np.zeros((8,8))
checker[1::2,1::2]=1
checker[::2,::2]=1
print(checker)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
index_value=np.unravel_index(99,(6,7,8))
print(index_value)

(1, 5, 3)
